export const GENRE_PRIMARY_OPTIONS = [
  // 'Afro House',
  'Afro',
  'Ambient',
  'Blues',
  'Breaks',
  'Classical',
  'Country',
  // 'Deep House',
  'Disco',
  'Drum & Bass',
  'Dubstep',
  // 'Electro House',
  // 'Electro',
  'Electronic',
  'Experimental',
  'Funk',
  // 'Future Bass',
  // 'Future House',
  // 'Hard Techno',
  'Hardcore',
  'Hardstyle',
  'Hip Hop',
  'House',
  'Indie Dance',
  'Jazz',
  'Latin',
  // 'Liquid Drum & Bass',
  // 'Melodic Dubstep',
  // 'Melodic Techno',
  'Metal',
  // 'Neurofunk',
  'Nu Disco',
  // 'Organic House',
  'Pop',
  // 'Progressive House',
  // 'Progressive Trance',
  'Psytrance',
  'R&B',
  'Reggae',
  'Rock',
  'Soul',
  // 'Tech House',
  'Techno',
  'Trance',
  'Trap',
]
